### ISSUE TITLE
404 Error for PastiOblique Font

### ISSUE THREAD

**Issue by PitchBlackNights** [project-undefined/project-undefined-website#14]
Website links to these 404ing URLs
```
http://localhost:5173/fonts/pasti-font/PastiOblique-7B0wK.otf
```

Files that link to that URLs
Links Font -- [~/projectundefined/src/global.scss:14](https://github.com/project-undefined/project-undefined-website/blob/8aa8d38301ae101e9dbe080da57e8f5466cb9e35/projectundefined/src/global.scss#L14)

**Comment by wsdevv** [comment]
Yeah, for some reason the public folder was removed during merging of a branch. I sadly have no .svg backups of the logo. Only a screenshot.

**Comment by PitchBlackNights** [comment]
Okay... Well I have edited the logo that you had in that screenshot. I posted it in the discord, and we might be able to remake the image

**Comment by PitchBlackNights** [comment]
I mostly just meant this issue to be a reminder for us to fix that. It was just a thing that I noticed when I cloned the repo today

**Comment by PitchBlackNights** [comment]
actually, we still can keep the reminder for the font

**Comment by wsdevv** [comment]
PastiOblique font is able to be reached eventually, it just looks like the vite server doesn't seem to serve it right away on page load, so It's not really a problem. I faked the svg with a png for now.
